services:
  userservice_db:
    container_name: userservice_db
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass
    volumes:
      - userservice_db_data:/var/lib/postgresql/data

  userservice:
    container_name: userservice
    build:
      context: userservice
    ports:
      - "8008:8008"
    restart: always
    environment:
      - PORT=8008
      - DB_URL=postgres://postgres:pass@userservice_db:5432/postgres
      - SECRET=FBJHFBKL89547395743FDJKHGD4854306734076403HFS87970
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=events
    depends_on:
      - userservice_db
      - taskservice
      - kafka
    links:
      - taskservice
      - kafka

  taskservice_db:
    container_name: taskservice_db
    image: postgres:12.8
    restart: always
    environment:
      - POSTGRES_PASSWORD=pass
    volumes:
      - taskservice_db_data:/var/lib/postgresql/data

  taskservice:
    container_name: taskservice
    build:
      context: taskservice
    ports:
      - "50051:50051"
    restart: always
    environment:
      - PORT=50051
      - DB_URL=postgres://postgres:pass@taskservice_db:5432/postgres
    depends_on:
      - taskservice_db

  statisticsservice_db:
    container_name: statisticsservice_db
    image: yandex/clickhouse-server:latest
    volumes:
      - statisticsservice_db_data:/var/lib/clickhouse
    restart: always

  statisticsservice:
    container_name: statisticsservice
    build:
      context: statisticsservice
    ports:
      - "8080:8080"
    restart: always
    environment:
      - PORT=8080
      - DB_URL=tcp://statisticsservice_db:9000?username=default&password=&database=default
      - KAFKA_BROKER=kafka:9092
      - KAFKA_TOPIC=events
    depends_on:
      - statisticsservice_db
      - kafka
    links:
      - statisticsservice_db
      - kafka

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.0.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

volumes:
  userservice_db_data:
  taskservice_db_data:
  statisticsservice_db_data: